/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteRouteImport } from './routes/_layout/index/route'
import { Route as LayoutActivitiesRouteRouteImport } from './routes/_layout/activities/route'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRouteRoute = LayoutIndexRouteRouteImport.update({
  id: '/',
  path: '',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutActivitiesRouteRoute = LayoutActivitiesRouteRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRouteRoute
  '/activities': typeof LayoutActivitiesRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof LayoutIndexRouteRoute
  '/activities': typeof LayoutActivitiesRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/': typeof LayoutIndexRouteRoute
  '/_layout/activities': typeof LayoutActivitiesRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/activities'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/activities'
  id: '__root__' | '/_layout' | '/_layout/' | '/_layout/activities'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/activities': {
      id: '/_layout/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof LayoutActivitiesRouteRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutIndexRouteRoute: typeof LayoutIndexRouteRoute
  LayoutActivitiesRouteRoute: typeof LayoutActivitiesRouteRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutIndexRouteRoute: LayoutIndexRouteRoute,
  LayoutActivitiesRouteRoute: LayoutActivitiesRouteRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
